name = "Hugo Pavilion Product"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"
custom_js = ['js/navbar.js']

[author]
  name = ""
  homepage = ""
